"""Writes the problem slots for the authoring batches. Each slot: (id, topic, difficulty, figure, skill)."""
import json, os

M, H = "medium", "hard"
SLOTS = {
    "PROBABILITY": [  # weakest area: 1 of 4 correct on probability
        (M, False, "probability of two dependent events (drawing without replacement)"),
        (H, False, "probability of at least one success over several independent trials (complement)"),
        (M, False, "conditional probability from a two-way table (table field)"),
        (H, False, "conditional probability from a two-way table where the condition is a column total (table field)"),
        (M, True, "probability with a Venn diagram of two overlapping groups"),
        (H, False, "counting arrangements with a restriction (permutations)"),
        (M, False, "counting combinations (choose a committee)"),
        (H, False, "probability using combinations (choose 2 of n with a condition)"),
        (M, False, "expected value of a simple game"),
        (H, True, "geometric probability: chance a random point in a square lands in a shaded circle"),
        (M, False, "probability of A or B with overlap (inclusion-exclusion)"),
        (H, False, "probability that two dice sum to a value or meet a condition"),
        (M, False, "experimental vs. theoretical probability from frequency data (table field)"),
        (H, False, "probability that a randomly chosen integer in a range meets a divisibility condition"),
        (M, True, "spinner with unequal sector angles; probability from central angles"),
        (H, False, "find an unknown count so that a probability equals a given value"),
    ],
    "RATIOS": [
        (M, False, "split a total in a 3-part ratio"),
        (H, False, "ratio changes after some items are added; find the original count"),
        (M, False, "unit rate and cost comparison"),
        (H, False, "inverse proportion: workers and time"),
        (M, False, "combined work rates (two pipes fill a tank)"),
        (H, False, "chained ratios a:b and b:c to a:c, then a quantity"),
        (M, True, "map scale with a drawn rectangle; actual area (scale squared)"),
        (H, True, "similar triangles in a shadow or ladder setup; find a length"),
        (M, False, "unit conversion across two rates (feet per second to miles per hour)"),
        (H, False, "mixture problem with two concentrations"),
        (M, False, "direct variation: y varies directly with x"),
        (H, False, "y varies inversely with the square of x"),
        (M, False, "recipe scaling with fractions"),
        (H, False, "average speed for a round trip at two different speeds"),
    ],
    "PERCENT": [
        (M, False, "successive percent increase and decrease"),
        (H, False, "find the original price after a discount and a tax"),
        (M, False, "percent change between two values"),
        (H, False, "percent of a percent: part of a group that is part of a larger group"),
        (M, True, "read a bar graph and compute a percent increase between two bars"),
        (H, False, "simple vs. compound interest over a few years"),
        (M, False, "percent of a total from a table of categories (table field)"),
        (H, False, "a quantity is p% more than one value and q% less than another; relate them"),
    ],
    "WORD_PROBLEMS": [
        (M, False, "translate a cost situation into a linear equation and solve"),
        (H, False, "system of two equations from a ticket or coin situation"),
        (M, True, "read a line graph of distance vs. time; find a rate"),
        (H, False, "linear model from two data points; predict a value"),
        (M, False, "consecutive integers with a sum condition"),
        (H, False, "age problem with a future condition"),
        (M, False, "inequality from a budget constraint; maximum whole number of items"),
        (H, True, "read a table-like graph of two phone plans; find where costs are equal"),
        (M, False, "perimeter word problem leading to a linear equation"),
        (H, False, "work backward through several percent and fraction steps"),
        (M, False, "interpret slope and intercept of a linear model in context"),
        (H, False, "break-even point from revenue and cost functions"),
    ],
    "EXPONENTS": [
        (M, False, "simplify a product and quotient of monomials with negative exponents"),
        (H, False, "solve an exponential equation by matching bases (powers of 2 or 3)"),
        (M, False, "evaluate a fractional exponent"),
        (H, False, "simplify a sum of radicals that need simplifying first"),
        (M, False, "rationalize a denominator"),
        (H, False, "exponential growth: doubling time"),
        (M, False, "scientific notation product or quotient"),
        (H, False, "exponent rules with a variable exponent: 2^(x+3) - 2^x"),
        (M, False, "power of a product with a coefficient"),
        (H, False, "exponential decay model; find the value after t periods"),
    ],
    "REWRITING": [
        (M, False, "solve a formula for one variable (several steps)"),
        (H, False, "solve a rational formula for a variable that appears twice"),
        (M, False, "solve a linear equation with fractions"),
        (H, False, "solve an absolute value equation; sum of solutions"),
        (M, False, "solve a literal equation with a squared variable"),
        (H, False, "equivalent expression by factoring out a common binomial"),
        (M, False, "solve a linear inequality with a negative coefficient"),
        (H, False, "solve a radical equation and reject the extraneous root"),
    ],
    "FUNCTIONS": [
        (M, False, "evaluate a composite function f(g(x))"),
        (H, False, "find the inverse of a linear or rational function"),
        (M, True, "read values from the graph of a function"),
        (H, True, "graph transformation: which equation matches a shifted graph"),
        (M, False, "function notation with an expression input f(x+2)"),
        (H, False, "piecewise function evaluation at a boundary"),
        (M, False, "domain of a function with a square root or denominator"),
        (H, True, "read a function graph to count solutions of f(x) = k"),
        (M, False, "average rate of change over an interval"),
        (H, False, "find a constant so that f(a) equals a value"),
    ],
    "QUADRATICS": [
        (M, False, "solve a quadratic by factoring"),
        (H, False, "sum and product of roots from coefficients"),
        (M, True, "vertex and axis of symmetry from a graphed parabola"),
        (H, False, "complete the square to find the vertex"),
        (M, False, "use the quadratic formula; simplify the radical"),
        (H, True, "projectile height graph: time to reach maximum height"),
        (M, False, "multiply and simplify polynomials"),
        (H, False, "discriminant: values of k for two real solutions"),
        (M, False, "factor a difference of squares"),
        (H, False, "polynomial remainder or a factor test"),
    ],
    "AREA_VOLUME": [
        (M, True, "area of a composite figure: rectangle with a semicircle"),
        (H, True, "shaded region between a square and an inscribed circle"),
        (M, True, "volume of a cylinder from a figure"),
        (H, False, "scaling: radius and height change; new volume ratio"),
        (M, True, "area of a trapezoid with a missing height found by the Pythagorean theorem"),
        (H, True, "surface area of a rectangular box with labeled edges"),
        (M, False, "perimeter given area and a length-width relation"),
        (H, True, "arc length and sector area in a circle with a central angle"),
        (M, True, "area of a triangle on a coordinate grid"),
        (H, False, "volume of a cone vs. a cylinder with the same base"),
        (M, False, "circle: area from circumference"),
        (H, True, "rectangle inscribed in a circle; find the circle area"),
    ],
    "ANGLES": [
        (M, True, "parallel lines cut by a transversal; find an angle"),
        (H, True, "two transversals and parallel lines; angle chase to an unknown"),
        (M, True, "triangle angle sum with an exterior angle"),
        (H, True, "isosceles triangle with tick marks; find a base angle"),
        (M, False, "interior angle of a regular polygon"),
        (H, True, "similar triangles with a parallel segment inside a triangle; find a length"),
        (M, True, "Pythagorean theorem in a right triangle with one leg unknown"),
        (H, True, "special right triangle (30-60-90) inside a figure"),
        (M, True, "vertical and supplementary angles at two intersecting lines"),
        (H, False, "number of sides of a regular polygon from an exterior angle condition"),
    ],
    "SLOPE": [
        (M, False, "equation of a line through two points"),
        (H, True, "perpendicular line through a point shown on a graph"),
        (M, False, "slope of a line in standard form"),
        (H, False, "midpoint and distance between two points"),
        (M, True, "read slope and y-intercept from a graphed line"),
        (H, False, "equation of a circle from center and a point on it"),
        (M, False, "parallel line through a point"),
        (H, True, "find the intersection point of two graphed lines"),
        (M, False, "find k so that two lines are parallel"),
        (H, False, "center and radius of a circle from an equation (complete the square)"),
    ],
    "UNIT_CIRCLE": [
        (M, False, "exact value of sin or cos at a special angle in radians"),
        (H, False, "given sin and the quadrant, find tan"),
        (M, True, "right triangle trig: find a side using sin, cos, or tan"),
        (H, True, "angle of elevation word problem with a diagram"),
        (M, False, "convert degrees to radians"),
        (H, False, "trig identity: sin^2 + cos^2 = 1 to find a value"),
        (M, True, "unit circle point coordinates for an angle"),
        (H, False, "period and amplitude of a sinusoidal function"),
    ],
    "LAW_SINES_COSINES": [
        (M, True, "law of cosines: find a side, given two sides and the included angle"),
        (H, True, "law of sines: choose the right expression for a side"),
        (M, False, "law of cosines: find cos of an angle from three sides"),
        (H, True, "law of sines word problem with two observers"),
    ],
    "LOGARITHMS": [
        (M, False, "rewrite a log equation in exponential form"),
        (H, False, "log rules: expand or combine to evaluate"),
        (M, False, "evaluate a log with a fractional or reciprocal argument"),
        (H, False, "solve a log equation; check the domain"),
        (M, False, "change of base or comparing log values"),
        (H, False, "solve an exponential equation with logs"),
    ],
    "STATISTICS": [
        (M, False, "mean after adding or removing a value"),
        (H, False, "find a missing score to reach a target mean"),
        (M, True, "median and range from a dot plot"),
        (H, True, "read a scatterplot and its line of best fit; predict"),
        (M, False, "weighted average of two groups"),
        (H, False, "effect of adding a constant or multiplying on mean and standard deviation"),
        (M, True, "read a histogram to find a count or a percent"),
        (H, False, "median of a frequency table (table field)"),
    ],
    "FRACTIONS": [
        (M, False, "arithmetic sequence: find the nth term"),
        (H, False, "geometric sequence: find a term or a ratio"),
        (M, False, "complex numbers: multiply and simplify i^2"),
        (H, False, "complex fraction simplification with variables"),
    ],
}

PREFIX = {"PROBABILITY": "PROB", "RATIOS": "RAT", "PERCENT": "PCT", "WORD_PROBLEMS": "WORD", "EXPONENTS": "EXP",
          "REWRITING": "REW", "FUNCTIONS": "FUN", "QUADRATICS": "QUAD", "AREA_VOLUME": "AREA", "ANGLES": "ANG",
          "SLOPE": "COORD", "UNIT_CIRCLE": "TRIG", "LAW_SINES_COSINES": "LAW", "LOGARITHMS": "LOG",
          "STATISTICS": "STAT", "FRACTIONS": "NUM"}

BATCHES = [
    ["PROBABILITY", "PERCENT"],
    ["RATIOS", "WORD_PROBLEMS"],
    ["EXPONENTS", "REWRITING", "LOGARITHMS"],
    ["FUNCTIONS", "QUADRATICS", "FRACTIONS"],
    ["AREA_VOLUME", "ANGLES"],
    ["SLOPE", "UNIT_CIRCLE", "LAW_SINES_COSINES", "STATISTICS"],
]

os.makedirs("slots", exist_ok=True)
total = figs = 0
for n, topics in enumerate(BATCHES, 1):
    out = []
    for t in topics:
        for i, (diff, fig, skill) in enumerate(SLOTS[t], 1):
            out.append({"id": f"{PREFIX[t]}-{i:02d}", "topic": t, "difficulty": diff, "figure": fig, "skill": skill})
    json.dump(out, open(f"slots/batch{n}.json", "w"), indent=1)
    total += len(out); figs += sum(s["figure"] for s in out)
    print(f"batch{n}: {len(out)} slots, {sum(s['figure'] for s in out)} figures")
print("total", total, "figures", figs, f"({figs/total:.0%})")
